docs/team/darshan152.md

Adding PPP Skeleton for Darshan

Add PPP for Darshan

---

docs/team/huimin.md

Added Project Portfolio Page (PPP) as huimin.md. Part of #10.

Create skeletal PPP for Hui Min

---

docs/team/onefangg.md

Add Yi Fang's PPP

---

build.gradle
docs/DeveloperGuide.md

* Mark order
* Unmark order
* Clear customers

Add user story and use case to developer guide

---

docs/DeveloperGuide.md

Part of #64 
Add and update use cases for adding a customer and an order

Update use cases for adding a customer and an order

---

src/main/java/seedu/address/logic/commands/ListPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Passed both gradle checkstyle and tests.
Will work on ExitCommand next.

Refactor ListCommand to ListPersonCommand

---

src/main/java/seedu/address/logic/commands/MarkOrderCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/MarkOrderCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/order/Complete.java
src/main/java/seedu/address/model/order/Details.java
src/main/java/seedu/address/model/order/Order.java
src/main/java/seedu/address/storage/JsonAdaptedOrder.java
src/main/java/seedu/address/ui/OrderCard.java
src/main/resources/view/OrderListCard.fxml
src/test/java/seedu/address/model/ModelStub.java

part of #24 
Test cases not yet completed.

Mark order

---

src/main/java/seedu/address/logic/commands/AddOrderCommand.java
src/main/java/seedu/address/logic/commands/MarkOrderCommand.java
src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
src/test/java/seedu/address/logic/commands/ListOrderCommandTest.java
src/test/java/seedu/address/logic/commands/MarkOrderCommandTest.java
src/test/java/seedu/address/testutil/OrderBuilder.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalOrders.java

Also resolve addo message usage bug

Create test for mark order, delete order, list order

---

src/main/java/seedu/address/logic/commands/FindPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java

#55 
Change all usages of `FindCommand` to `FindPersonCommand`

Refactor FindCommand to FindPersonCommand

---

src/main/java/seedu/address/logic/commands/UnmarkOrderCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/MarkOrderCommandParser.java
src/main/java/seedu/address/logic/parser/UnmarkOrderCommandParser.java

Add unmark command

---

src/main/java/seedu/address/model/order/Complete.java
src/main/java/seedu/address/storage/JsonAdaptedOrder.java

Renaming method to make it easier to understand

Rename Complete class method

---

src/main/resources/view/HelpWindow.css

The colors of the HelpWindow and the CopyURL button are now consistent with ReadyBakey's theme.
No further changes for HelpWindow UI.
Closes #25

Update HelpWindow CSS

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ResponseDisplay.java
src/main/resources/view/ReadyBakeyTheme.css
src/main/resources/view/ResponseDisplay.fxml

- clearer boolean attribute and method names
- more appropriate variable naming

Update UI naming convention

---

src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/model/person/PersonTest.java

Removes unique constraint for name. As discussed.

Impose unique phone number constraint on person

---

src/main/java/seedu/address/ui/MainWindow.java

bug due to using filtered list in displaying of orders

Fix bug of null order details

---

src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/testutil/TypicalAddressBook.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalPersons.java

DeleteOrderCommand checks for orders of the person and throws a command exception if an order is found,
Test for deletion also added.

Add restriction to disallow person from being deleted when they have an order

---

docs/UserGuide.md
src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/FindOrderCollectionTypeCommand.java
src/main/java/seedu/address/logic/commands/FindOrderCommand.java
src/main/java/seedu/address/logic/commands/FindOrderDetailsCommand.java
src/main/java/seedu/address/logic/commands/FindOrderRemarkCommand.java
src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
src/main/java/seedu/address/model/order/CollectionTypeContainsKeywordsPredicate.java
src/main/java/seedu/address/model/order/DetailsContainsKeywordsPredicate.java
src/main/java/seedu/address/model/order/Order.java
src/main/java/seedu/address/model/order/RemarkContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/Remark.java
src/test/java/seedu/address/logic/commands/FindOrderCollectionTypeCommandTest.java
src/test/java/seedu/address/logic/commands/FindOrderDetailsCommandTest.java
src/test/java/seedu/address/logic/commands/FindOrderNameCommandTest.java
src/test/java/seedu/address/logic/commands/FindOrderPhoneCommandTest.java
src/test/java/seedu/address/logic/commands/FindOrderRemarkCommandTest.java
src/test/java/seedu/address/testutil/TypicalOrders.java

Lets implement find order for details, collectiontype and remarks and its corresponding predicates it uses for filtering
Lets also implement the necessary tests for find order - name, phone, details, collectiontype, remarks
Closes #13 & #33

Implement find order command features for additional order attributes

---

docs/UserGuide.md

Lets update user guide for find order command

Update User Guide for `findo`

---

src/main/java/seedu/address/model/order/DateChecker.java

DateChecker had one line of code that did not adhere to checkstyle standards. I have edited the line but am not sure how it managed to slip through the checkstyle previously.

Edit DateChecker

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/AddOrderCommand.java
src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/order/Order.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/OrderListPanel.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/model/ModelStub.java

Changing references of `Model.getFilteredxxxList` to `Model.getxxxList` where the new method will return the full list of the orders/persons

Bug null order details

---

docs/UserGuide.md

Lets input findo into  our command summary

Update UG to include findo in the command summary

---

docs/UserGuide.md

* Update clear usage
* Align between findo and findp description

Update UG with update findp command

---

src/main/java/seedu/address/logic/commands/AddOrderCommand.java
src/main/java/seedu/address/logic/commands/AddPersonCommand.java
src/main/java/seedu/address/logic/commands/FindOrderCommand.java

Lets
* Change Remark to being an optional argument for addOrder
* Change Remark to being an optional argument for addPerson
* Edit Message Usage for findo

Description fixes for addOrder, addPerson and findOrder commands

---

src/main/java/seedu/address/logic/commands/EditOrderCommand.java

Update EditOrderCommand Usage with new detalis format

---

docs/UserGuide.md

UG now contains information regarding the character restrictions for the person prefix inputs.

Update UG for defense

---

src/main/resources/view/ReadyBakeyTheme.css

Code reuse for scrollbar CSS. Added the reference.

Update code reuse reference

---

src/main/java/seedu/address/model/order/DateChecker.java

Reused the calculation from the specified website. Website only listed one calculation and the rest are created by me based on my understanding of the code snippet provided. Everything in the switch case statement was created by me.

Update code reuse for DateChecker

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

Change sampled data tags to be more specific to bakers context

---

docs/UserGuide.md

resolves #185 
Summary table still shows clearp instead of clear for the command input, changed it to clear

Update UserGuide.md with correct clear command in summary table

---

src/main/java/seedu/address/model/order/Details.java
src/test/java/seedu/address/model/order/DetailsTest.java

... when there are more than one whitespace between words

Fix bug where invalid details are thrown

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

resolves #201 
Added a character limit of 70 on tags

Add char limit for tags

---

docs/UserGuide.md

resolves #206 
resolves #205 
Adding in information on behavior of tags in addp and editp command

Update user guide with tags information

---

docs/_sass/minima/_base.scss
docs/team/punnyhuimin.md

Also updated the content header so that it says ReadyBakey instead of AB3 when converting to PDF.

Update PPP to fit page limit

---

docs/UserGuide.md

Update UG to re-organise features

---

docs/DeveloperGuide.md
src/main/java/seedu/address/model/order/Complete.java
src/main/java/seedu/address/storage/JsonAdaptedOrder.java

Update naming to better meet naming conventions of the module

Change naming of complete value

---

docs/DeveloperGuide.md
docs/SettingUp.md
docs/team/geralddtan.md
src/main/java/seedu/address/model/order/DeliveryDateTime.java

* Add Table of Contents to Developer Guide & Settingup
* Edit PPP
* Edit DG
* Updated documentation for code reuse block - DeliveryDateTime#isLeapYear

Documentation Changes

---

docs/AboutUs.md
docs/team/darshan152.md

Updated my PPP as well as a small formatting issue in the AboutUs page

Update PPP and AboutUs pages

---

docs/team/punnyhuimin.md

Indented numbers not registering as a proper number list.

Update PPP format issues

---

docs/team/punnyhuimin.md

PPP formatting was wrong, edited to be pointers instead.

Address PPP issues

---

docs/DeveloperGuide.md

TOC updated to include sub points for ease of reading. Corrected misspellings and corrected links pointing to AB3 still.

Update DG Table of Contents

---

docs/UserGuide.md

Update UG for window resize
